[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
pelite = { workspace = true }
nix = { workspace = true }
libc = { workspace = true }
serde = { workspace = true }

shared = { version = "0.1.0", path = "../shared" }

[build-dependencies]
shared = { version = "0.1.0", path = "../shared" }