[package]
name = "gubtool"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }

engine = { path = "../engine" }
darksouls2 = { version = "0.1.0", path = "../darksouls2" }
eldenring = { version = "0.1.0", path = "../eldenring" }
tui = { path = "../tui" }

[lints]
workspace = true