[package]
name = "config"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
ratatui-themes = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
strum = { workspace = true }

gubtool-core = { version = "0.1.0", path = "../gubtool-core" }
darksouls2 = { version = "0.1.0", path = "../darksouls2" }
eldenring = { version = "0.1.0", path = "../eldenring" }

[lints]
workspace = true
