[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

gubtool-core = { version = "0.1.0", path = "../gubtool-core" }
utils = { version = "0.1.0", path = "../utils" }

[lints]
workspace = true